theme: jekyll-theme-minimal
title: Creative Approaches to Emerging Technology
description: Camille's blog and homework assignments for Creative Approaches to Emerging Technology at Olin College of Engineering.
